---
env:
  # Provide a list of OSes we want to use for testing.
  - distro: ubuntu1404
  - distro: ubuntu1604

services:
  # Tell Travis to start Docker when it brings up an environment.
  - docker

script:
  # Run tests.
  - ${PWD}/tests/test.sh

  # Check for the Music Player Daemon process
#  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ps -ef | grep mpd | grep -v grep'

  # Check for the Music Player Daemon control port
#  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ss -lnt | grep 6600'

  # Check for the Music Player Daemon HTTPD out port
#  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ss -lnt | grep 8000'

notifications:
  # Notify Ansible Galaxy when a role builds successfully.
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
