---
# tasks file for ansible-install-mpd

- name: Make group for Music Player Daemon user
  group:
    name: "{{ ansible_install_mpd_user }}"
    state: present
  tags:
    - ansible-install-mpd
    - users

- name: Make user for Music Player Daemon
  user:
    name: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    home: "{{ ansible_install_mpd_home }}"
    comment: "Music Player Daemon"
  tags:
    - ansible-install-mpd
    - users

- name: Create needed directories
  file:
    path: "{{ item }}"
    owner: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ ansible_install_mpd_src_base }}"
    - "{{ ansible_install_mpd_music_directory }}"
    - "{{ ansible_install_mpd_playlist_directory }}"
  tags:
    - ansible-install-mpd
    - files

- name: Download and extract tar package
  unarchive:
    remote_src: yes
    dest: "{{ ansible_install_mpd_src_base }}"
    owner: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    src: "{{ ansible_install_mpd_url_base }}/{{ ansible_install_mpd_filename }}"
    creates: "{{ ansible_install_mpd_src }}"
  tags:
    - ansible-install-mpd
    - files

- name: Add ubuntu-toolchain-r/test PPA
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - ansible-install-mpd
    - packages

- name: Install pre-requisites
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    state: latest
  with_items:
    - "{{ ansible_install_mpd_apt_prereqs }}"
  tags:
    - ansible-install-mpd
    - packages

- name: Create softlink for gcc-4.9
  file:
    path: /usr/bin/gcc
    src: /usr/bin/gcc-4.9
    state: link
  tags:
    - ansible-install-mpd
    - files

- name: Create softlink for g++-4.9
  file:
    path: /usr/bin/g++
    src: /usr/bin/g++-4.9
    state: link
  tags:
    - ansible-install-mpd
    - files

- name: Configure source before make
  command: "{{ ansible_install_mpd_src }}/configure -q --enable-httpd-output --enable-shout --enable-vorbis"
  args:
    chdir: "{{ ansible_install_mpd_src }}"
    creates: "{{ ansible_install_mpd_src }}/Makefile"
  become_user: "{{ ansible_install_mpd_user }}"
  tags:
    - ansible-install-mpd
    - files

- name: See if executable already exists
  stat:
    get_checksum: False
    get_md5: False
    path: "{{ ansible_install_mpd_src }}/src/mpd"
  register: stat_output_exec
  tags:
    - ansible-install-mpd
    - files

- name: If not, use make to compile the source
  make:
    chdir: "{{ ansible_install_mpd_src }}"
  become_user: "{{ ansible_install_mpd_user }}"
  when: not stat_output_exec.stat.exists
  tags:
    - ansible-install-mpd
    - files

- name: See if executable is already installed
  stat:
    get_checksum: False
    get_md5: False
    path: "{{ ansible_install_mpd_executable }}"
  register: stat_output_install
  tags:
    - ansible-install-mpd
    - files

- name: If not, use make to install the compiled source
  make:
    chdir: "{{ ansible_install_mpd_src }}"
    target: install
  when: not stat_output_install.stat.exists
  tags:
    - ansible-install-mpd
    - files

# Validation in the template tasks below fail because the file ansible 
# uses to validate don't work, so we'll use a separate task.
- name: Generate upstart configuration file
  template:
    dest: "{{ ansible_install_mpd_upstart_dest }}"
    group: root
    owner: root
    mode: 0644
    src: "{{ ansible_install_mpd_upstart_src }}"
  when: ansible_service_mgr == "upstart"
  notify: Restart the Music Player Daemon service
  register: upstart_template_output
  tags:
    - ansible-install-mpd
    - files
    - services

- name: Validate upstart configuration file if new
  command: "init-checkconf {{ ansible_install_mpd_upstart_dest }}"
  when: upstart_template_output.changed
  tags:
    - ansible-install-mpd
    - files
    - services

- name: Generate systemd service configuration file
  template:
    dest: "{{ ansible_install_mpd_systemd_service_dest }}"
    group: root
    owner: root
    mode: 0644
    src: "{{ ansible_install_mpd_systemd_service_src }}"
  when: ansible_service_mgr == "systemd"
  notify: Restart the Music Player Daemon service
  register: systemd_service_template_output
  tags:
    - ansible-install-mpd
    - files
    - services

- name: Generate systemd socket configuration file
  template:
    dest: "{{ ansible_install_mpd_systemd_socket_dest }}"
    group: root
    owner: root
    mode: 0644
    src: "{{ ansible_install_mpd_systemd_socket_src }}"
  when: ansible_service_mgr == "systemd"
  notify: Restart the Music Player Daemon service
  register: systemd_socket_template_output
  tags:
    - ansible-install-mpd
    - files
    - services

- name: Validate systemd configuration files if new
  command: "systemd-analyze verify {{ ansible_install_mpd_systemd_service_dest }}"
  when: systemd_service_template_output.changed or systemd_socket_template_output.changed
  tags:
    - ansible-install-mpd
    - files
    - services

- name: Generate MPD configuration file
  template:
    dest: "{{ ansible_install_mpd_conf }}"
    owner: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    mode: 0644
    src: "{{ ansible_install_mpd_conf_src }}"
  notify: Restart the Music Player Daemon service
  tags:
    - ansible-install-mpd
    - files

- name: Enable the Music Player Daemon service on next boot
  service:
    name: mpd
    enabled: yes
  tags:
    - ansible-install-mpd
    - services

- name: Touch some needed files
  file:
    path: "{{ item }}"
    owner: "{{ ansible_install_mpd_user }}"
    group: "{{ ansible_install_mpd_group }}"
    state: touch
    mode: 0755
  with_items:
    - "{{ ansible_install_mpd_db_file }}"
    - "{{ ansible_install_mpd_pid_file }}"
    - "{{ ansible_install_mpd_ratings_file }}"
    - "{{ ansible_install_mpd_state_file }}"
  changed_when: False
  tags:
    - ansible-install-mpd
    - files
