---
# handlers file for ansible-install-mpd
- name: Validate systemd configuration files if new | COMMAND
  command: "systemd-analyze verify {{ ansible_install_mpd_systemd_service_dest }}"
  when: systemd_service_template_output.changed
  tags:
    - ansible-install-mpd
    - files
- name: Restart the Music Player Daemon service | SERVICE
  service:
    name: mpd
    state: restarted
  tags:
    - ansible-install-mpd
    - services
...